### PR TITLE
Update TransferAccessMessage.getMessageSequenceNumber()

### PR DESCRIPTION
**Pull request by alextaka**
Change to return byte, rather than int.

### CODE REVIEW

**Comment by alextaka** [comment]
@leshi PTAL. All tests pass

**Review by leshi — CHANGES_REQUESTED** [review]
Does this not require a change in some test or some other code?

**Comment by alextaka** [comment]
The current tests test valid values for bytes, so they all pass, as you can compare ints from -128 to 127 with bytes. 

The underlying value was already a byte, it was just _returning_ an integer. The tests were not set up to try to assign non-byte values. No code currently calls this function (it will be used in future PRs) except for the tests.

**Review by leshi — APPROVED** [review]

**Comment by leshi** [comment]
LGTM

**Pull request merged**
